// LSB (Legacy Standard Bible) verses - Verse of the Day
// © 2021 The Lockman Foundation. Used by permission. LSBible.org
const LSB_VERSES = [
  { ref: "John 3:16", text: "For God so loved the world, that He gave His only begotten Son, that whoever believes in Him shall not perish, but have eternal life." },
  { ref: "Psalm 23:1", text: "Yahweh is my shepherd; I shall not want." },
  { ref: "Jeremiah 29:11", text: "For I know the plans that I have for you, declares Yahweh, plans for welfare and not for calamity to give you a future and a hope." },
  { ref: "Philippians 4:13", text: "I can do all things through Him who strengthens me." },
  { ref: "Romans 8:28", text: "And we know that God causes all things to work together for good to those who love God, to those who are called according to His purpose." },
  { ref: "Proverbs 3:5-6", text: "Trust in Yahweh with all your heart and do not lean on your own understanding. In all your ways acknowledge Him, and He will make your paths straight." },
  { ref: "Isaiah 41:10", text: "Do not fear, for I am with you; do not anxiously look about you, for I am your God. I will strengthen you, surely I will help you, surely I will uphold you with My righteous right hand." },
  { ref: "Matthew 11:28", text: "Come to Me, all who are weary and heavy-laden, and I will give you rest." },
  { ref: "Psalm 46:1", text: "God is our refuge and strength, a very present help in trouble." },
  { ref: "Romans 12:2", text: "And do not be conformed to this world, but be transformed by the renewing of your mind, so that you may prove what the will of God is, that which is good and acceptable and perfect." },
  { ref: "Joshua 1:9", text: "Have I not commanded you? Be strong and courageous! Do not tremble or be dismayed, for Yahweh your God is with you wherever you go." },
  { ref: "Psalm 119:105", text: "Your word is a lamp to my feet and a light to my path." },
  { ref: "Isaiah 40:31", text: "Yet those who wait for Yahweh will gain new strength; they will mount up with wings like eagles, they will run and not get tired, they will walk and not become weary." },
  { ref: "Philippians 4:6-7", text: "Be anxious for nothing, but in everything by prayer and supplication with thanksgiving let your requests be made known to God. And the peace of God, which surpasses all comprehension, will guard your hearts and your minds in Christ Jesus." },
  { ref: "2 Timothy 1:7", text: "For God has not given us a spirit of timidity, but of power and love and discipline." },
  { ref: "Psalm 27:1", text: "Yahweh is my light and my salvation; whom shall I fear? Yahweh is the defense of my life; whom shall I dread?" },
  { ref: "Matthew 28:19-20", text: "Go therefore and make disciples of all the nations, baptizing them in the name of the Father and the Son and the Holy Spirit, teaching them to observe all that I commanded you; and lo, I am with you always, even to the end of the age." },
  { ref: "John 14:6", text: "Jesus said to him, I am the way, and the truth, and the life; no one comes to the Father but through Me." },
  { ref: "Romans 3:23", text: "For all have sinned and fall short of the glory of God." },
  { ref: "Romans 6:23", text: "For the wages of sin is death, but the free gift of God is eternal life in Christ Jesus our Lord." },
  { ref: "Ephesians 2:8-9", text: "For by grace you have been saved through faith; and that not of yourselves, it is the gift of God; not as a result of works, so that no one may boast." },
  { ref: "John 1:12", text: "But as many as received Him, to them He gave the right to become children of God, even to those who believe in His name." },
  { ref: "1 John 1:9", text: "If we confess our sins, He is faithful and righteous to forgive us our sins and to cleanse us from all unrighteousness." },
  { ref: "Psalm 34:4", text: "I sought Yahweh, and He answered me and delivered me from all my fears." },
  { ref: "Proverbs 16:3", text: "Commit your works to Yahweh and your plans will be established." },
  { ref: "Isaiah 43:2", text: "When you pass through the waters, I will be with you; and through the rivers, they will not overflow you. When you walk through the fire, you will not be scorched, nor will the flame burn you." },
  { ref: "Matthew 6:33", text: "But seek first His kingdom and His righteousness, and all these things will be added to you." },
  { ref: "Psalm 121:1-2", text: "I will lift up my eyes to the mountains; from where shall my help come? My help comes from Yahweh, who made heaven and earth." },
  { ref: "Hebrews 11:1", text: "Now faith is the assurance of things hoped for, the conviction of things not seen." },
  { ref: "Colossians 3:23", text: "Whatever you do, do your work heartily, as for the Lord rather than for men." },
  { ref: "Psalm 37:4", text: "Delight yourself in Yahweh; and He will give you the desires of your heart." },
  { ref: "Proverbs 22:6", text: "Train up a child in the way he should go, even when he is old he will not depart from it." },
  { ref: "1 Corinthians 13:4-5", text: "Love is patient, love is kind and is not jealous; love does not brag and is not arrogant, does not act unbecomingly; it does not seek its own, is not provoked, does not take into account a wrong suffered." },
  { ref: "Galatians 5:22-23", text: "But the fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, self-control; against such things there is no law." },
  { ref: "Romans 5:8", text: "But God demonstrates His own love toward us, in that while we were yet sinners, Christ died for us." },
  { ref: "John 15:12", text: "This is My commandment, that you love one another, just as I have loved you." },
  { ref: "1 Peter 5:7", text: "Casting all your anxiety on Him, because He cares for you." },
  { ref: "Psalm 91:1-2", text: "He who dwells in the secret place of the Most High will abide in the shadow of the Almighty. I will say to Yahweh, My refuge and my fortress, my God, in whom I trust!" },
  { ref: "Isaiah 26:3", text: "The steadfast of mind You will keep in perfect peace, because he trusts in You." },
  { ref: "Psalm 139:14", text: "I will give thanks to You, for I am fearfully and wonderfully made; wonderful are Your works, and my soul knows it very well." },
  { ref: "Proverbs 3:3", text: "Do not let kindness and truth leave you; bind them around your neck, write them on the tablet of your heart." },
  { ref: "Micah 6:8", text: "He has told you, O man, what is good; and what does Yahweh require of you but to do justice, to love kindness, and to walk humbly with your God?" },
  { ref: "Matthew 5:14", text: "You are the light of the world. A city set on a hill cannot be hidden." },
  { ref: "Psalm 19:14", text: "Let the words of my mouth and the meditation of my heart be acceptable in Your sight, O Yahweh, my rock and my Redeemer." },
  { ref: "James 1:5", text: "But if any of you lacks wisdom, let him ask of God, who gives to all generously and without reproach, and it will be given to him." },
  { ref: "Psalm 32:8", text: "I will instruct you and teach you in the way which you should go; I will counsel you with My eye upon you." },
  { ref: "Isaiah 55:8-9", text: "For My thoughts are not your thoughts, nor are your ways My ways, declares Yahweh. For as the heavens are higher than the earth, so are My ways higher than your ways and My thoughts than your thoughts." },
  { ref: "Romans 10:9", text: "That if you confess with your mouth Jesus as Lord, and believe in your heart that God raised Him from the dead, you will be saved." },
  { ref: "Psalm 118:24", text: "This is the day which Yahweh has made; let us rejoice and be glad in it." },
  { ref: "Proverbs 18:10", text: "The name of Yahweh is a strong tower; the righteous runs into it and is safe." },
  { ref: "John 10:10", text: "The thief comes only to steal and kill and destroy; I came that they may have life, and have it abundantly." },
  { ref: "2 Corinthians 5:17", text: "Therefore if anyone is in Christ, he is a new creature; the old things passed away; behold, new things have come." },
  { ref: "Psalm 46:10", text: "Cease striving and know that I am God; I will be exalted among the nations, I will be exalted in the earth." },
  { ref: "Isaiah 53:5", text: "But He was pierced through for our transgressions, He was crushed for our iniquities; the chastening for our well-being fell upon Him, and by His scourging we are healed." },
  { ref: "Matthew 7:7", text: "Ask, and it will be given to you; seek, and you will find; knock, and it will be opened to you." },
  { ref: "Psalm 103:12", text: "As far as the east is from the west, so far has He removed our transgressions from us." },
  { ref: "Proverbs 31:25", text: "Strength and dignity are her clothing, and she smiles at the future." },
  { ref: "Romans 8:38-39", text: "For I am convinced that neither death, nor life, nor angels, nor principalities, nor things present, nor things to come, nor powers, nor height, nor depth, nor any other created thing, will be able to separate us from the love of God, which is in Christ Jesus our Lord." },
  { ref: "Psalm 147:3", text: "He heals the brokenhearted and binds up their wounds." },
  { ref: "Isaiah 40:8", text: "The grass withers, the flower fades, but the word of our God stands forever." },
  { ref: "Matthew 6:34", text: "So do not worry about tomorrow; for tomorrow will care for itself. Each day has enough trouble of its own." },
  { ref: "Psalm 34:8", text: "O taste and see that Yahweh is good; how blessed is the man who takes refuge in Him!" },
  { ref: "Proverbs 12:25", text: "Anxiety in a man's heart weighs it down, but a good word makes it glad." },
  { ref: "John 8:12", text: "Then Jesus again spoke to them, saying, I am the Light of the world; he who follows Me will not walk in the darkness, but will have the Light of life." },
  { ref: "Psalm 51:10", text: "Create in me a clean heart, O God, and renew a steadfast spirit within me." },
  { ref: "Isaiah 43:19", text: "Behold, I will do something new, now it will spring forth; will you not be aware of it? I will even make a roadway in the wilderness, rivers in the wasteland." },
  { ref: "Matthew 22:37", text: "And He said to him, You shall love the Lord your God with all your heart, and with all your soul, and with all your mind." },
  { ref: "Psalm 90:12", text: "So teach us to number our days, that we may present to You a heart of wisdom." },
  { ref: "Proverbs 4:23", text: "Watch over your heart with all diligence, for from it flow the springs of life." },
  { ref: "Romans 12:12", text: "Rejoicing in hope, persevering in tribulation, devoted to prayer." },
  { ref: "Psalm 56:3", text: "When I am afraid, I will put my trust in You." },
  { ref: "Isaiah 54:10", text: "For the mountains may be removed and the hills may shake, but My lovingkindness will not be removed from you, and My covenant of peace will not be shaken, says Yahweh who has compassion on you." },
  { ref: "Matthew 17:20", text: "And He said to them, Because of the littleness of your faith; for truly I say to you, if you have faith the size of a mustard seed, you will say to this mountain, Move from here to there, and it will move; and nothing will be impossible to you." },
  { ref: "Psalm 145:9", text: "Yahweh is good to all, and His mercies are over all His works." },
  { ref: "Proverbs 16:9", text: "The mind of man plans his way, but Yahweh directs his steps." },
  { ref: "1 Thessalonians 5:16-18", text: "Rejoice always; pray without ceasing; in everything give thanks; for this is God's will for you in Christ Jesus." },
  { ref: "Psalm 62:5", text: "My soul, wait in silence for God only, for my hope is from Him." },
  { ref: "Isaiah 55:6", text: "Seek Yahweh while He may be found; call upon Him while He is near." },
  { ref: "Matthew 5:16", text: "Let your light shine before men in such a way that they may see your good works, and glorify your Father who is in heaven." },
  { ref: "Psalm 73:26", text: "My flesh and my heart may fail, but God is the strength of my heart and my portion forever." },
  { ref: "Proverbs 17:22", text: "A joyful heart is good medicine, but a broken spirit dries up the bones." },
  { ref: "Hebrews 13:5", text: "Make sure that your character is free from the love of money, being content with what you have; for He Himself has said, I will never desert you, nor will I ever forsake you." },
  { ref: "Psalm 86:5", text: "For You, Lord, are good, and ready to forgive, and abundant in lovingkindness to all who call upon You." },
  { ref: "Isaiah 30:21", text: "Your ears will hear a word behind you, This is the way, walk in it, whenever you turn to the right or to the left." },
  { ref: "Matthew 21:22", text: "And all things you ask in prayer, believing, you will receive." },
  { ref: "Psalm 100:4", text: "Enter His gates with thanksgiving and His courts with praise. Give thanks to Him, bless His name." },
  { ref: "Proverbs 20:7", text: "A righteous man who walks in his integrity—how blessed are his sons after him." },
  { ref: "James 4:8", text: "Draw near to God and He will draw near to you. Cleanse your hands, you sinners; and purify your hearts, you double-minded." },
  { ref: "Psalm 119:11", text: "Your word I have treasured in my heart, that I may not sin against You." },
  { ref: "Isaiah 43:1", text: "But now, thus says Yahweh, your Creator, O Jacob, and He who formed you, O Israel, Do not fear, for I have redeemed you; I have called you by name; you are Mine!" },
  { ref: "Matthew 7:12", text: "In everything, therefore, treat people the same way you want them to treat you, for this is the Law and the Prophets." },
  { ref: "Psalm 138:3", text: "On the day I called, You answered me; You made me bold with strength in my soul." },
  { ref: "Proverbs 31:30", text: "Charm is deceitful and beauty is vain, but a woman who fears Yahweh, she shall be praised." },
  { ref: "1 John 4:18", text: "There is no fear in love; but perfect love casts out fear, because fear involves punishment, and the one who fears is not perfected in love." },
  { ref: "Psalm 143:8", text: "Let me hear Your lovingkindness in the morning; for I trust in You; teach me the way in which I should walk; for to You I lift up my soul." },
  { ref: "Isaiah 9:6", text: "For a child will be born to us, a son will be given to us; and the government will rest on His shoulders; and His name will be called Wonderful Counselor, Mighty God, Eternal Father, Prince of Peace." },
  { ref: "Matthew 28:6", text: "He is not here, for He has risen, just as He said. Come, see the place where He was lying." },
  { ref: "Psalm 150:6", text: "Let everything that has breath praise Yahweh. Praise Yahweh!" },
  { ref: "Proverbs 14:30", text: "A tranquil heart is life to the body, but passion is rottenness to the bones." },
  { ref: "2 Corinthians 12:9", text: "And He has said to me, My grace is sufficient for you, for power is perfected in weakness. Most gladly, therefore, I will rather boast about my weaknesses, so that the power of Christ may dwell in me." },
  { ref: "Psalm 16:8", text: "I have set Yahweh continually before me; because He is at my right hand, I will not be shaken." },
  { ref: "Isaiah 53:6", text: "All of us like sheep have gone astray, each of us has turned to his own way; but Yahweh has caused the iniquity of us all to fall on Him." },
  { ref: "Matthew 6:9-10", text: "Pray, then, in this way: Our Father who is in heaven, hallowed be Your name. Your kingdom come. Your will be done, on earth as it is in heaven." },
  { ref: "Psalm 18:2", text: "Yahweh is my rock and my fortress and my deliverer, my God, my rock, in whom I take refuge; my shield and the horn of my salvation, my stronghold." },
  { ref: "Proverbs 11:25", text: "The generous man will be prosperous, and he who waters will himself be watered." },
  { ref: "Ephesians 4:32", text: "Be kind to one another, tender-hearted, forgiving each other, just as God in Christ also has forgiven you." },
  { ref: "Psalm 25:4", text: "Make me know Your ways, O Yahweh; teach me Your paths." },
  { ref: "Isaiah 33:2", text: "O Yahweh, be gracious to us; we have waited for You. Be their strength every morning, our salvation also in the time of distress." },
  { ref: "Matthew 6:14", text: "For if you forgive others for their transgressions, your heavenly Father will also forgive you." },
  { ref: "Psalm 29:11", text: "Yahweh will give strength to His people; Yahweh will bless His people with peace." },
  { ref: "Proverbs 15:1", text: "A gentle answer turns away wrath, but a harsh word stirs up anger." },
  { ref: "Galatians 6:9", text: "Let us not lose heart in doing good, for in due time we will reap if we do not grow weary." },
  { ref: "Psalm 40:1", text: "I waited patiently for Yahweh; and He inclined to me and heard my cry." },
  { ref: "Isaiah 65:24", text: "It will also come to pass that before they call, I will answer; and while they are still speaking, I will hear." },
  { ref: "Matthew 5:44", text: "But I say to you, love your enemies and pray for those who persecute you." },
  { ref: "Psalm 55:22", text: "Cast your burden upon Yahweh and He will sustain you; He will never allow the righteous to be shaken." },
  { ref: "Proverbs 19:21", text: "Many plans are in a man's heart, but the counsel of Yahweh will stand." },
  { ref: "1 Corinthians 16:14", text: "Let all that you do be done in love." },
  { ref: "Psalm 68:19", text: "Blessed be the Lord, who daily bears our burden, the God who is our salvation." },
  { ref: "Isaiah 12:2", text: "Behold, God is my salvation, I will trust and not be afraid; for Yahweh God is my strength and song, and He has become my salvation." },
  { ref: "Matthew 9:37-38", text: "Then He said to His disciples, The harvest is plentiful, but the workers are few. Therefore beseech the Lord of the harvest to send out workers into His harvest." },
  { ref: "Psalm 84:11", text: "For Yahweh God is a sun and shield; Yahweh gives grace and glory; no good thing does He withhold from those who walk uprightly." },
  { ref: "Proverbs 28:26", text: "He who trusts in his own heart is a fool, but he who walks wisely will be delivered." },
  { ref: "Colossians 3:12", text: "So, as those who have been chosen of God, holy and beloved, put on a heart of compassion, kindness, humility, gentleness and patience." },
  { ref: "Psalm 91:11", text: "For He will give His angels charge concerning you, to guard you in all your ways." },
  { ref: "Isaiah 26:4", text: "Trust in Yahweh forever, for in Yahweh God you have an everlasting Rock." },
  { ref: "Matthew 10:31", text: "So do not fear; you are more valuable than many sparrows." },
  { ref: "Psalm 103:2", text: "Bless Yahweh, O my soul, and forget none of His benefits." },
  { ref: "Proverbs 3:11-12", text: "My son, do not reject the discipline of Yahweh or loathe His reproof, for whom Yahweh loves He reproves, even as a father corrects the son in whom he delights." },
  { ref: "1 Peter 2:9", text: "But you are a chosen race, a royal priesthood, a holy nation, a people for God's own possession, so that you may proclaim the excellencies of Him who has called you out of darkness into His marvelous light." },
  { ref: "Psalm 107:1", text: "Oh give thanks to Yahweh, for He is good, for His lovingkindness is everlasting." },
  { ref: "Isaiah 55:1", text: "Ho! Every one who thirsts, come to the waters; and you who have no money come, buy and eat. Come, buy wine and milk without money and without cost." },
  { ref: "Matthew 11:29", text: "Take My yoke upon you and learn from Me, for I am gentle and humble in heart, and you will find rest for your souls." },
  { ref: "Psalm 116:1", text: "I love Yahweh, because He hears my voice and my supplications." },
  { ref: "Proverbs 10:22", text: "It is the blessing of Yahweh that makes rich, and He adds no sorrow to it." },
  { ref: "Hebrews 4:16", text: "Therefore let us draw near with confidence to the throne of grace, so that we may receive mercy and find grace to help in time of need." },
  { ref: "Psalm 121:7-8", text: "Yahweh will protect you from all evil; He will keep your soul. Yahweh will guard your going out and your coming in from this time forth and forever." },
  { ref: "Isaiah 35:4", text: "Say to those with anxious heart, Take courage, fear not. Behold, your God will come with vengeance; the recompense of God will come, but He will save you." },
  { ref: "Matthew 18:20", text: "For where two or three have gathered together in My name, I am there in their midst." },
  { ref: "Psalm 130:5", text: "I wait for Yahweh, my soul does wait, and in His word do I hope." },
  { ref: "Proverbs 13:12", text: "Hope deferred makes the heart sick, but desire fulfilled is a tree of life." },
  { ref: "James 1:17", text: "Every good thing given and every perfect gift is from above, coming down from the Father of lights, with whom there is no variation or shifting shadow." },
  { ref: "Psalm 136:1", text: "Give thanks to Yahweh, for He is good, for His lovingkindness is everlasting." },
  { ref: "Isaiah 44:22", text: "I have wiped out your transgressions like a thick cloud and your sins like a heavy mist. Return to Me, for I have redeemed you." },
  { ref: "Matthew 25:40", text: "And the King will answer and say to them, Truly I say to you, to the extent that you did it to one of these brothers of Mine, even the least of them, you did it to Me." },
  { ref: "Psalm 139:23-24", text: "Search me, O God, and know my heart; try me and know my anxious thoughts; and see if there be any hurtful way in me, and lead me in the everlasting way." },
  { ref: "Proverbs 29:25", text: "The fear of man brings a snare, but he who trusts in Yahweh will be exalted." },
  { ref: "1 John 3:1", text: "See how great a love the Father has bestowed on us, that we would be called children of God; and such we are. For this reason the world does not know us, because it did not know Him." },
  { ref: "Psalm 145:18", text: "Yahweh is near to all who call upon Him, to all who call upon Him in truth." },
  { ref: "Isaiah 50:4", text: "The Lord Yahweh has given Me the tongue of disciples, that I may know how to sustain the weary one with a word. He awakens Me morning by morning, He awakens My ear to listen as a disciple." },
  { ref: "Matthew 6:21", text: "For where your treasure is, there your heart will be also." },
  { ref: "Psalm 1:1-2", text: "How blessed is the man who does not walk in the counsel of the wicked, nor stand in the path of sinners, nor sit in the seat of scoffers! But his delight is in the law of Yahweh, and in His law he meditates day and night." },
  { ref: "Proverbs 2:6", text: "For Yahweh gives wisdom; from His mouth come knowledge and understanding." },
  { ref: "Romans 15:13", text: "Now may the God of hope fill you with all joy and peace in believing, so that you will abound in hope by the power of the Holy Spirit." },
  { ref: "Psalm 4:8", text: "In peace I will both lie down and sleep, for You alone, O Yahweh, make me to dwell in safety." },
  { ref: "Isaiah 58:11", text: "And Yahweh will continually guide you, and satisfy your desire in scorched places, and give strength to your bones; and you will be like a watered garden, and like a spring of water whose waters do not fail." },
  { ref: "Matthew 7:11", text: "If you then, being evil, know how to give good gifts to your children, how much more will your Father who is in heaven give what is good to those who ask Him!" },
  { ref: "Psalm 9:1", text: "I will give thanks to Yahweh with all my heart; I will tell of all Your wonders." },
  { ref: "Proverbs 6:20-21", text: "My son, observe the commandment of your father and do not forsake the teaching of your mother; bind them continually on your heart; tie them around your neck." },
  { ref: "2 Peter 3:9", text: "The Lord is not slow about His promise, as some count slowness, but is patient toward you, not wishing for any to perish but for all to come to repentance." },
  { ref: "Psalm 13:5", text: "But I have trusted in Your lovingkindness; my heart shall rejoice in Your salvation." },
  { ref: "Isaiah 61:1", text: "The Spirit of the Lord Yahweh is upon me, because Yahweh has anointed me to bring good news to the afflicted; He has sent me to bind up the brokenhearted, to proclaim liberty to captives and freedom to prisoners." },
  { ref: "Matthew 12:50", text: "For whoever does the will of My Father who is in heaven, he is My brother and sister and mother." },
  { ref: "Psalm 20:4", text: "May He grant you your heart's desire and fulfill all your counsel!" },
  { ref: "Proverbs 8:17", text: "I love those who love me; and those who diligently seek me will find me." },
  { ref: "Revelation 3:20", text: "Behold, I stand at the door and knock; if anyone hears My voice and opens the door, I will come in to him and will dine with him, and he with Me." },
  { ref: "Psalm 28:7", text: "Yahweh is my strength and my shield; my heart trusts in Him, and I am helped; therefore my heart exults, and with my song I shall thank Him." },
  { ref: "Isaiah 64:8", text: "But now, O Yahweh, You are our Father, we are the clay, and You our potter; and all of us are the work of Your hand." },
  { ref: "Matthew 16:24", text: "Then Jesus said to His disciples, If anyone wishes to come after Me, he must deny himself, and take up his cross and follow Me." },
  { ref: "Psalm 31:24", text: "Be strong and let your heart take courage, all you who hope in Yahweh." },
  { ref: "Proverbs 9:10", text: "The fear of Yahweh is the beginning of wisdom, and the knowledge of the Holy One is understanding." },
  { ref: "John 15:5", text: "I am the vine, you are the branches; he who abides in Me and I in him, he bears much fruit, for apart from Me you can do nothing." },
  { ref: "Psalm 33:4", text: "For the word of Yahweh is upright, and all His work is done in faithfulness." },
  { ref: "Isaiah 66:13", text: "As one whom his mother comforts, so I will comfort you; and you will be comforted in Jerusalem." },
  { ref: "Matthew 19:26", text: "And looking at them Jesus said to them, With people this is impossible, but with God all things are possible." },
  { ref: "Psalm 37:5", text: "Commit your way to Yahweh, trust also in Him, and He will do it." },
  { ref: "Proverbs 14:26", text: "In the fear of Yahweh there is strong confidence, and his children will have refuge." },
  { ref: "John 14:27", text: "Peace I leave with you; My peace I give to you; not as the world gives do I give to you. Do not let your heart be troubled, nor let it be fearful." },
  { ref: "Psalm 40:3", text: "He put a new song in my mouth, a song of praise to our God; many will see and fear and will trust in Yahweh." },
  { ref: "Isaiah 7:14", text: "Therefore the Lord Himself will give you a sign: Behold, a virgin will be with child and bear a son, and she will call His name Immanuel." },
  { ref: "Matthew 26:41", text: "Keep watching and praying that you may not enter into temptation; the spirit is willing, but the flesh is weak." },
  { ref: "Psalm 42:11", text: "Why are you in despair, O my soul? And why have you become disturbed within me? Hope in God, for I shall yet praise Him, the help of my countenance and my God." },
  { ref: "Proverbs 15:3", text: "The eyes of Yahweh are in every place, watching the evil and the good." },
  { ref: "Acts 1:8", text: "But you will receive power when the Holy Spirit has come upon you; and you shall be My witnesses both in Jerusalem, and in all Judea and Samaria, and even to the remotest part of the earth." },
  { ref: "Psalm 51:12", text: "Restore to me the joy of Your salvation and sustain me with a willing spirit." },
  { ref: "Isaiah 25:1", text: "O Yahweh, You are my God; I will exalt You, I will give thanks to Your name; for You have worked wonders, plans formed long ago, with perfect faithfulness." },
  { ref: "Matthew 5:9", text: "Blessed are the peacemakers, for they shall be called sons of God." },
  { ref: "Psalm 59:16", text: "But as for me, I shall sing of Your strength; yes, I shall joyfully sing of Your lovingkindness in the morning, for You have been my stronghold and a refuge in the day of my distress." },
  { ref: "Proverbs 16:24", text: "Pleasant words are a honeycomb, sweet to the soul and healing to the bones." },
  { ref: "Romans 14:8", text: "For if we live, we live for the Lord, or if we die, we die for the Lord; therefore whether we live or die, we are the Lord's." },
  { ref: "Psalm 66:20", text: "Blessed be God, who has not turned away my prayer nor His lovingkindness from me." },
  { ref: "Isaiah 33:6", text: "And He will be the stability of your times, a wealth of salvation, wisdom and knowledge; the fear of Yahweh is his treasure." },
  { ref: "Matthew 5:3", text: "Blessed are the poor in spirit, for theirs is the kingdom of heaven." },
  { ref: "Psalm 71:14", text: "But as for me, I will hope continually, and will praise You yet more and more." },
  { ref: "Proverbs 20:11", text: "It is by his deeds that a lad distinguishes himself if his conduct is pure and right." },
  { ref: "1 Corinthians 10:13", text: "No temptation has overtaken you but such as is common to man; and God is faithful, who will not allow you to be tempted beyond what you are able, but with the temptation will provide the way of escape also, so that you will be able to endure it." },
  { ref: "Psalm 77:14", text: "You are the God who works wonders; You have made known Your strength among the peoples." },
  { ref: "Isaiah 40:29", text: "He gives strength to the weary, and to him who lacks might He increases power." },
  { ref: "Matthew 6:6", text: "But you, when you pray, go into your inner room, close your door and pray to your Father who is in secret, and your Father who sees what is done in secret will reward you." },
  { ref: "Psalm 86:15", text: "But You, O Lord, are a God merciful and gracious, slow to anger and abundant in lovingkindness and truth." },
  { ref: "Proverbs 22:1", text: "A good name is to be more desired than great wealth, favor is better than silver and gold." },
  { ref: "Ephesians 6:10", text: "Finally, be strong in the Lord and in the strength of His might." },
  { ref: "Psalm 94:19", text: "When my anxious thoughts multiply within me, Your consolations delight my soul." },
  { ref: "Isaiah 49:16", text: "Behold, I have inscribed you on the palms of My hands; your walls are continually before Me." },
  { ref: "Matthew 7:24", text: "Therefore everyone who hears these words of Mine and acts on them, may be compared to a wise man who built his house on the rock." },
  { ref: "Psalm 103:13", text: "Just as a father has compassion on his children, so Yahweh has compassion on those who fear Him." },
  { ref: "Proverbs 24:16", text: "For a righteous man falls seven times, and rises again, but the wicked stumble in time of calamity." },
  { ref: "Philippians 1:6", text: "For I am confident of this very thing, that He who began a good work in you will perfect it until the day of Christ Jesus." },
  { ref: "Psalm 112:7", text: "He will not fear evil tidings; his heart is steadfast, trusting in Yahweh." },
  { ref: "Isaiah 55:3", text: "Incline your ear and come to Me. Listen, that you may live; and I will make an everlasting covenant with you, according to the faithful mercies shown to David." },
  { ref: "Matthew 10:39", text: "He who has found his life will lose it, and he who has lost his life for My sake will find it." },
  { ref: "Psalm 119:130", text: "The unfolding of Your words gives light; it gives understanding to the simple." },
  { ref: "Proverbs 27:17", text: "Iron sharpens iron, so one man sharpens another." },
  { ref: "2 Timothy 2:15", text: "Be diligent to present yourself approved to God as a workman who does not need to be ashamed, accurately handling the word of truth." },
  { ref: "Psalm 121:3", text: "He will not allow your foot to slip; He who keeps you will not slumber." },
  { ref: "Isaiah 55:12", text: "For you will go out with joy and be led forth with peace; the mountains and the hills will break forth into shouts of joy before you, and all the trees of the field will clap their hands." },
  { ref: "Matthew 13:43", text: "Then the righteous will shine forth as the sun in the kingdom of their Father. He who has ears, let him hear." },
  { ref: "Psalm 130:7", text: "O Israel, hope in Yahweh; for with Yahweh there is lovingkindness, and with Him is abundant redemption." },
  { ref: "Proverbs 30:5", text: "Every word of God is tested; He is a shield to those who take refuge in Him." },
  { ref: "Titus 3:5", text: "He saved us, not on the basis of deeds which we have done in righteousness, but according to His mercy, by the washing of regeneration and renewing by the Holy Spirit." },
  { ref: "Psalm 139:17", text: "How precious also are Your thoughts to me, O God! How vast is the sum of them!" },
  { ref: "Isaiah 55:7", text: "Let the wicked forsake his way and the unrighteous man his thoughts; and let him return to Yahweh, and He will have compassion on him, and to our God, for He will abundantly pardon." },
  { ref: "Matthew 18:4", text: "Whoever then humbles himself as this child, he is the greatest in the kingdom of heaven." },
  { ref: "Psalm 145:14", text: "Yahweh sustains all who fall and raises up all who are bowed down." },
  { ref: "Proverbs 31:26", text: "She opens her mouth in wisdom, and the teaching of kindness is on her tongue." },
  { ref: "Hebrews 11:6", text: "And without faith it is impossible to please Him, for he who comes to God must believe that He is and that He is a rewarder of those who seek Him." },
  { ref: "Psalm 147:11", text: "Yahweh takes pleasure in those who fear Him, in those who hope in His lovingkindness." },
  { ref: "Isaiah 53:4", text: "Surely our griefs He Himself bore, and our sorrows He carried; yet we ourselves esteemed Him stricken, smitten of God, and afflicted." },
  { ref: "Matthew 25:21", text: "His master said to him, Well done, good and faithful slave. You were faithful with a few things, I will put you in charge of many things; enter into the joy of your master." },
  { ref: "Psalm 150:1", text: "Praise Yahweh! Praise God in His sanctuary; praise Him in His mighty expanse." },
  { ref: "Proverbs 1:7", text: "The fear of Yahweh is the beginning of knowledge; fools despise wisdom and instruction." },
  { ref: "1 Peter 5:10", text: "After you have suffered for a little while, the God of all grace, who called you to His eternal glory in Christ, will Himself perfect, confirm, strengthen and establish you." },
];
